require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WritersController do

  # This should return the minimal set of attributes required to create a valid
  # Writer. As you add validations to Writer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WritersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all writers as @writers" do
      writer = Writer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:writers).should eq([writer])
    end
  end

  describe "GET show" do
    it "assigns the requested writer as @writer" do
      writer = Writer.create! valid_attributes
      get :show, {:id => writer.to_param}, valid_session
      assigns(:writer).should eq(writer)
    end
  end

  describe "GET new" do
    it "assigns a new writer as @writer" do
      get :new, {}, valid_session
      assigns(:writer).should be_a_new(Writer)
    end
  end

  describe "GET edit" do
    it "assigns the requested writer as @writer" do
      writer = Writer.create! valid_attributes
      get :edit, {:id => writer.to_param}, valid_session
      assigns(:writer).should eq(writer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Writer" do
        expect {
          post :create, {:writer => valid_attributes}, valid_session
        }.to change(Writer, :count).by(1)
      end

      it "assigns a newly created writer as @writer" do
        post :create, {:writer => valid_attributes}, valid_session
        assigns(:writer).should be_a(Writer)
        assigns(:writer).should be_persisted
      end

      it "redirects to the created writer" do
        post :create, {:writer => valid_attributes}, valid_session
        response.should redirect_to(Writer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved writer as @writer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Writer.any_instance.stub(:save).and_return(false)
        post :create, {:writer => {}}, valid_session
        assigns(:writer).should be_a_new(Writer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Writer.any_instance.stub(:save).and_return(false)
        post :create, {:writer => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested writer" do
        writer = Writer.create! valid_attributes
        # Assuming there are no other writers in the database, this
        # specifies that the Writer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Writer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => writer.to_param, :writer => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested writer as @writer" do
        writer = Writer.create! valid_attributes
        put :update, {:id => writer.to_param, :writer => valid_attributes}, valid_session
        assigns(:writer).should eq(writer)
      end

      it "redirects to the writer" do
        writer = Writer.create! valid_attributes
        put :update, {:id => writer.to_param, :writer => valid_attributes}, valid_session
        response.should redirect_to(writer)
      end
    end

    describe "with invalid params" do
      it "assigns the writer as @writer" do
        writer = Writer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Writer.any_instance.stub(:save).and_return(false)
        put :update, {:id => writer.to_param, :writer => {}}, valid_session
        assigns(:writer).should eq(writer)
      end

      it "re-renders the 'edit' template" do
        writer = Writer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Writer.any_instance.stub(:save).and_return(false)
        put :update, {:id => writer.to_param, :writer => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested writer" do
      writer = Writer.create! valid_attributes
      expect {
        delete :destroy, {:id => writer.to_param}, valid_session
      }.to change(Writer, :count).by(-1)
    end

    it "redirects to the writers list" do
      writer = Writer.create! valid_attributes
      delete :destroy, {:id => writer.to_param}, valid_session
      response.should redirect_to(writers_url)
    end
  end

end
